In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import time
import numpy as np
import pandas as pd
import numpy as np
import os
from tensorflow.keras.preprocessing.image import ImageDataGenerator, img_to_array, load_img, array_to_img
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Flatten, MaxPooling2D, Dropout, BatchNormalization
from tensorflow.keras.optimizers import SGD
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import sys
import sklearn.metrics
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.models import load_model

In [2]:
model=load_model("sam.h5")
model = tf.keras.models.Model(inputs=[model.input], outputs=[model.output])
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_input (InputLayer)    [(None, 300, 300, 3)]     0         
_________________________________________________________________
conv2d (Conv2D)              (None, 150, 150, 32)      2432      
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 75, 75, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 75, 75, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 37, 37, 64)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 37, 37, 128)       73856     
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 37, 37, 256)       295168

In [60]:
IMAGE_DIMS = (300, 300, 3)
batch_size=64
test_dir = r'F:/Work/casting_data/test'

In [77]:
##### Renaming of batch size concept for testing purpose #

test_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale = 1/255.)

n_test = sum([len(files) for r, d, files in os.walk(test_dir)])

test_generator = test_datagen.flow_from_directory(directory = test_dir,
                                                 # batch_size = n_test,
                                                batch_size = 1,
                                                  target_size = (IMAGE_DIMS[0], IMAGE_DIMS[1]),
                                                  class_mode = "categorical",
                                                  shuffle = False)

Found 715 images belonging to 2 classes.


In [78]:
class_labels = test_generator.class_indices
class_labels = {v: k for k, v in class_labels.items()}
classes = list(class_labels.values())

In [6]:
Y_pred = model.predict_generator(test_generator[101][0])

Instructions for updating:
Please use Model.predict, which supports generators.


In [7]:
Y_pred = model.predict(test_generator[101][0])

In [8]:
Y_pred

array([[0.93267065, 0.0673293 ]], dtype=float32)

In [15]:
from PIL import Image

In [50]:
# read image 
# convert into array 
# reshape and input into predict function


# open method used to open different extension image file
#im = Image.open(r"C:/Users/dell/Desktop/NDS/PI/def_front_bearing.png") 
im = Image.open(r"C:/Users/dell/Desktop/NDS/PI/ok_front_bearing.png")  
# This method will show image in any image viewer 
im.show() 

In [51]:
imgArray = np.array(im)
print(imgArray.shape)

(300, 300, 3)


In [52]:
print(imgArray.shape)

(300, 300, 3)


In [53]:
imgArray = np.expand_dims(imgArray, axis=0)

In [54]:
imgArray.shape

(1, 300, 300, 3)

In [55]:
Y_pred= model.predict(imgArray)

In [56]:
Y_pred

array([[0., 1.]], dtype=float32)

In [57]:
imgArray

array([[[[177, 177, 177],
         [177, 177, 177],
         [177, 177, 177],
         ...,
         [177, 177, 177],
         [176, 176, 176],
         [176, 176, 176]],

        [[178, 178, 178],
         [177, 177, 177],
         [177, 177, 177],
         ...,
         [172, 172, 172],
         [172, 172, 172],
         [173, 173, 173]],

        [[178, 178, 178],
         [178, 178, 178],
         [177, 177, 177],
         ...,
         [170, 170, 170],
         [171, 171, 171],
         [172, 172, 172]],

        ...,

        [[155, 155, 155],
         [154, 154, 154],
         [153, 153, 153],
         ...,
         [145, 145, 145],
         [144, 144, 144],
         [143, 143, 143]],

        [[151, 151, 151],
         [152, 152, 152],
         [153, 153, 153],
         ...,
         [145, 145, 145],
         [144, 144, 144],
         [143, 143, 143]],

        [[150, 150, 150],
         [152, 152, 152],
         [154, 154, 154],
         ...,
         [145, 145, 145],
        

In [88]:
test_generator[101][0]

array([[[[0.6392157 , 0.6392157 , 0.6392157 ],
         [0.64705884, 0.64705884, 0.64705884],
         [0.6627451 , 0.6627451 , 0.6627451 ],
         ...,
         [0.7372549 , 0.7372549 , 0.7372549 ],
         [0.7372549 , 0.7372549 , 0.7372549 ],
         [0.7372549 , 0.7372549 , 0.7372549 ]],

        [[0.63529414, 0.63529414, 0.63529414],
         [0.64705884, 0.64705884, 0.64705884],
         [0.65882355, 0.65882355, 0.65882355],
         ...,
         [0.7372549 , 0.7372549 , 0.7372549 ],
         [0.7372549 , 0.7372549 , 0.7372549 ],
         [0.7372549 , 0.7372549 , 0.7372549 ]],

        [[0.63529414, 0.63529414, 0.63529414],
         [0.6431373 , 0.6431373 , 0.6431373 ],
         [0.654902  , 0.654902  , 0.654902  ],
         ...,
         [0.7372549 , 0.7372549 , 0.7372549 ],
         [0.7372549 , 0.7372549 , 0.7372549 ],
         [0.7372549 , 0.7372549 , 0.7372549 ]],

        ...,

        [[0.5294118 , 0.5294118 , 0.5294118 ],
         [0.53333336, 0.53333336, 0.53333336]

In [63]:
imgArray = imgArray.reshape((-1, 300, 300, 
                            3))

In [64]:
imgArray.shape

(1, 300, 300, 3)

In [65]:
Y_pred= model.predict(imgArray)

In [67]:
Y_pred

array([[0., 1.]], dtype=float32)

In [84]:
arr1 = np.array(test_generator[101][0][0])
data1 = Image.fromarray((arr1 * 255).astype(np.uint8))
data1.save('def_front_bearing1.png')

In [85]:
imgArray=imgArray/255

In [86]:
imgArray


array([[[[0.69411765, 0.69411765, 0.69411765],
         [0.69411765, 0.69411765, 0.69411765],
         [0.69411765, 0.69411765, 0.69411765],
         ...,
         [0.69411765, 0.69411765, 0.69411765],
         [0.69019608, 0.69019608, 0.69019608],
         [0.69019608, 0.69019608, 0.69019608]],

        [[0.69803922, 0.69803922, 0.69803922],
         [0.69411765, 0.69411765, 0.69411765],
         [0.69411765, 0.69411765, 0.69411765],
         ...,
         [0.6745098 , 0.6745098 , 0.6745098 ],
         [0.6745098 , 0.6745098 , 0.6745098 ],
         [0.67843137, 0.67843137, 0.67843137]],

        [[0.69803922, 0.69803922, 0.69803922],
         [0.69803922, 0.69803922, 0.69803922],
         [0.69411765, 0.69411765, 0.69411765],
         ...,
         [0.66666667, 0.66666667, 0.66666667],
         [0.67058824, 0.67058824, 0.67058824],
         [0.6745098 , 0.6745098 , 0.6745098 ]],

        ...,

        [[0.60784314, 0.60784314, 0.60784314],
         [0.60392157, 0.60392157, 0.60392157]

In [108]:
test_dir = r'F:/sampletest'
test_generator = test_datagen.flow_from_directory(directory =test_dir,
                                                 # batch_size = n_test,
                                                batch_size = 1,
                                                  target_size = (300, 300),
                                                  #class_mode = "categorical",
                                                  shuffle = False)

Found 1 images belonging to 1 classes.


In [109]:
test_generator[0][0]

array([[[[0.69411767, 0.69411767, 0.69411767],
         [0.69411767, 0.69411767, 0.69411767],
         [0.69411767, 0.69411767, 0.69411767],
         ...,
         [0.69411767, 0.69411767, 0.69411767],
         [0.6901961 , 0.6901961 , 0.6901961 ],
         [0.6901961 , 0.6901961 , 0.6901961 ]],

        [[0.69803923, 0.69803923, 0.69803923],
         [0.69411767, 0.69411767, 0.69411767],
         [0.69411767, 0.69411767, 0.69411767],
         ...,
         [0.6745098 , 0.6745098 , 0.6745098 ],
         [0.6745098 , 0.6745098 , 0.6745098 ],
         [0.6784314 , 0.6784314 , 0.6784314 ]],

        [[0.69803923, 0.69803923, 0.69803923],
         [0.69803923, 0.69803923, 0.69803923],
         [0.69411767, 0.69411767, 0.69411767],
         ...,
         [0.6666667 , 0.6666667 , 0.6666667 ],
         [0.67058825, 0.67058825, 0.67058825],
         [0.6745098 , 0.6745098 , 0.6745098 ]],

        ...,

        [[0.60784316, 0.60784316, 0.60784316],
         [0.6039216 , 0.6039216 , 0.6039216 ]

In [110]:
Y_pred= model.predict(test_generator[0][0])
Y_pred

array([[0.21953058, 0.7804694 ]], dtype=float32)

In [98]:
test_generator[0][1]

array([[1.],
       [1.]], dtype=float32)

In [106]:
test_generator[1][0].shape

(1, 300, 300, 3)

In [107]:
Y_pred= model.predict(test_generator[1][0])
Y_pred

array([[0.21953058, 0.7804694 ]], dtype=float32)

In [101]:
test_generator[0][0][0].shape

(300, 300, 3)

In [113]:
test_generator[0][0].shape

(1, 300, 300, 3)

In [ ]:
#We have to store an image into directory and have to pass the array value that resprensts the array object#

In [117]:
test_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale = 1/255.)
test_dir = r'F:/sampletest'
test_generator = test_datagen.flow_from_directory(directory =test_dir,
                                                 # batch_size = n_test,
                                                batch_size = 1,
                                                  target_size = (300, 300),
                                                  #class_mode = "categorical",
                                                  shuffle = False)

Found 1 images belonging to 1 classes.


In [115]:
Y_pred= model.predict(test_generator[0][0])
Y_pred

array([[0.93267065, 0.0673293 ]], dtype=float32)

In [116]:
test_generator[0][0]

array([[[[0.6392157 , 0.6392157 , 0.6392157 ],
         [0.64705884, 0.64705884, 0.64705884],
         [0.6627451 , 0.6627451 , 0.6627451 ],
         ...,
         [0.7372549 , 0.7372549 , 0.7372549 ],
         [0.7372549 , 0.7372549 , 0.7372549 ],
         [0.7372549 , 0.7372549 , 0.7372549 ]],

        [[0.63529414, 0.63529414, 0.63529414],
         [0.64705884, 0.64705884, 0.64705884],
         [0.65882355, 0.65882355, 0.65882355],
         ...,
         [0.7372549 , 0.7372549 , 0.7372549 ],
         [0.7372549 , 0.7372549 , 0.7372549 ],
         [0.7372549 , 0.7372549 , 0.7372549 ]],

        [[0.63529414, 0.63529414, 0.63529414],
         [0.6431373 , 0.6431373 , 0.6431373 ],
         [0.654902  , 0.654902  , 0.654902  ],
         ...,
         [0.7372549 , 0.7372549 , 0.7372549 ],
         [0.7372549 , 0.7372549 , 0.7372549 ],
         [0.7372549 , 0.7372549 , 0.7372549 ]],

        ...,

        [[0.5294118 , 0.5294118 , 0.5294118 ],
         [0.53333336, 0.53333336, 0.53333336]